name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
          echo "This is a sample github action"
      - name: Now it is
        run: date
      - name: Directory Component
        run: ls -l